### PR TITLE
Account email search (frontend)

### LINKED ISSUE #98: [Access] [FE] Account email searching
## Context

We have an "Access Management" page that allows Angels Among Us admins to edit the permissions of the members on the site. This page is also used to give new members access to the platform. Right now, this page has a search bar that is not functional. Your job is to make this search bar work as intended.

## Requirements

The `account.search` API endpoint was implemented last sprint. Use this API endpoint to fetch accounts based on the `searchSubject`, which is the email typed in the search bar. It might be useful to modify the `account.search` endpoint to return all posts when the `searchSubject` is empty, and continue with the regex search when the `searchSubject` is not empty.

You should also create a `useDebounce` custom hook that will make sure we're not fetching too frequently from the API. Consider setting the debounce timeout to ~400ms. You will use this custom hook to control updates to the search input state. 

#### PM

- [ ] When I type in an email to the search bar, that email comes up
- [ ] When I type a substring that an email contains, that email will come up
- [ ] The search function is "live" and updates as I type (but not to the point the screen lags/becomes buggy)
- [ ] When I clear the search bar, every email shows up

#### EM

- [ ] Creation of `useDebounce` custom hook
- [ ] User input into the search bar correctly retrieves matching emails and displays them on the frontend
- [ ] API endpoint modified to retrieve all posts directly when input string is empty 

#### Designer

- [ ] Nothing design specific

### PR DESCRIPTION
**Pull request by aeluro1**
## Account email search(frontend)

Issue Number(s): #98

What does this PR change and why?

### Checklist

- [ ] Requirements have been implemented
- [ ] Acceptance criteria are met
- [ ] Database schema docs have been updated or are not necessary
- [ ] Code follows design and style guidelines
- [ ] Commits follow guidelines (concise, squashed, etc)
- [x] Relevant reviewers (Senior Dev/EM/Designers) have been assigned to this PR

### Critical Changes

- Database change/migration to run
- Environment config change
- Breaking API change

### Related PRs

- #number_of_pr

### Testing

Enumerate steps to test the functionality of your ticket. This should include edge cases and testing of error handling, if applicable.

### CODE REVIEW

**Review by katsukixyz — COMMENTED** [review]
Looking good - code looks great! It seems like typing in a search field that doesn't match any documents displays a spinner that doesn't go away. See if you can maintain and export some loading state within the `useDebounce` that is true when a user updates the value but the value hasn't been updated yet. Use this loading state and the loading value from the tRPC `useQuery` to only display a loading spinner when it's truly loading (value not updated in useDebounce or fetch is ongoing)

**Review by katsukixyz — COMMENTED** [review]
Looks great! Don't forget to update the API to return all posts when the searchSubject is empty, and do regex search when the searchSubject is not empty.

**Comment by aeluro1** [comment]
Doesn't the API endpoint already do this? When the search string is empty, the regex should match everything.

**Comment by katsukixyz** [comment]
It does, but I'm thinking a small performance optimization can be made if we are querying an empty string. In this case, we are guaranteed that we need to return all documents, so we can use `findAll` instead of `searchAccounts`. MongoDB is pretty performant, so I'm not sure what kind of improvement it will be, but what do you think?

**Comment by aeluro1** [comment]
> It does, but I'm thinking a small performance optimization can be made if we are querying an empty string. In this case, we are guaranteed that we need to return all documents, so we can use `findAll` instead of `searchAccounts`. MongoDB is pretty performant, so I'm not sure what kind of improvement it will be, but what do you think?

I see, fair point! `findAll` and `searchAccounts` both use mongoose's `find`, so at first glance it seems like they would perform the same. But just to be safe, I've made the minor change to the API.

**Review by katsukixyz — APPROVED** [review]
Looks good! Thanks for the changes 💯

**Pull request merged**
