### PR TITLE
Fix loading + mobile navbar

### PR DESCRIPTION
**Pull request by aeluro1**
## Fix bugs

Issue Number(s): #120 #130 #129 

Fixed minor bugs

### Checklist

- [ ] Requirements have been implemented
- [ ] Acceptance criteria are met
- [ ] Database schema docs have been updated or are not necessary
- [ ] Code follows design and style guidelines
- [ ] Commits follow guidelines (concise, squashed, etc)
- [x] Relevant reviewers (Senior Dev/EM/Designers) have been assigned to this PR

### CODE REVIEW

**Review by katsukixyz — COMMENTED** [review]
Nice stuff - I'll be making changes to the mobile navbar. Look out for a PR targeting this branch soon!

**Comment by aeluro1** [comment]
Sounds good! I did notice that the navbar has a `width=50%` applied to the links that's causing the profile picture to get squished and also creating scrollbars in smaller window sizes.

**Comment by katsukixyz** [comment]
Yeah, I noticed that too - gonna do a bit of a rewrite to make it work

**Review by katsukixyz — APPROVED** [review]
Excellent work! Everything looks good to me. Good job catching the scrollbar issues 💯

**Pull request merged**
